services:
  raspishika:
    image: raspishika
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./.env:/app/.env
      - ./database:/app/database
      - ./configs:/app/configs
