---
mainbot_commands:
  - week: Расписание на неделю
  - tomorrow: Расписание на завтра
  - left: Оставшиеся пары
  - quick: Расписание другой группы
  - teacher: Расписание преподавателя

  - settings: Меню настроек
  - group: Изменить группу
  - daily_time: Задать время рассылки
  - daily_off: Выключить рассылку
  - reminder_on: Включить напоминания перед парами
  - reminder_off: Выключить напоминания перед парами
  - access: Настройки доступа в группах

  - help: Список команд
  - stop: Остановить бота
  - start: Запустить бота
adminbot_commands:
  - stats: 'Send bot stats for period (default: 24h)'
  - distribution: 'Send distribution stats (args: dataKind, periodKind, period)'
  - config: Send config stats

  - chat: Send chat data view
  - group: Send group data view

  - start: Greet the admin
