---
telegram:
  token: ''
  admin_token: ''
  admin_id: 0
  my_commands:
    - week: Расписание на неделю
    - tomorrow: Расписание на завтра
    - left: Оставшиеся пары
    - quick: Расписание другой группы
    - teacher: Расписание преподавателя

    - settings: Меню настроек
    - group: Изменить группу
    - daily_time: Задать время рассылки
    - daily_off: Выключить рассылку
    - reminder_on: Включить напоминания перед парами
    - reminder_off: Выключить напоминания перед парами
    - access: Настройки доступа

    - help: Список команд
    - stop: Остановить бота
    - start: Запустить бота
  admin_commands:
    - stats: Get general statistics
features:
  admin_bot: false
  daily_sending: false
  pair_sending: false
database:
  file: database/db.sqlite3
browser:
  headless: true
  timeout: 30 # seconds
  screenshot_dir: storage/screenshots
cache:
  dir: storage/cache
  default_ttl: 10 # minutes
  schedule_ttl: 20 # minutes
  group_ttl: 7 # days
logger:
  level: debug

schedule_template: storage/schedule_template.html
