---
telegram:
  workers: 1
database:
  file: database/db.sqlite3
browser:
  headless: true
  timeout: 30 # seconds
  max_retries: 10
cache:
  default_ttl: 10 # minutes
  schedule_ttl: 20 # minutes
  group_ttl: 7 # days
logger:
  level: debug
features:
  admin_bot: false
  sending:
    daily: false
    pair_notification: false
    change_alert: false

sending:
  workers: 20
  pair_notificatoin:
    ttl: 90 # minutes
  change_alert:
    update_interval: 20 # minutes
