---
database:
  file: database/db.sqlite3
  migrations: database/migrations
browser:
  headless: true
  timeout: 30 # seconds
  max_retries: 3
  screenshot_dir: storage/screenshots
cache:
  dir: storage/cache
  default_ttl: 10 # minutes
  schedule_ttl: 20 # minutes
  group_ttl: 7 # days
logger:
  level: debug
  dir: storage/logs
features:
  admin_bot: false
  daily_sending: false
  pair_sending: false

pair_sending:
  notification_ttl: 90 # minutes
sending:
  workers: 20

schedule_template_file: storage/schedule_template.html
admin_config_file: configs/admin.json
